import json
import random
import socket
import time
from datetime import datetime, timezone


LOGSTASH_HOST = "logstash"
LOGSTASH_PORT = 5000


def generate_event():
    statuses = ["SUCCESS", "SUCCESS", "SUCCESS", "ERROR"]
    log_level = ["INFO", "INFO", "INFO", "ERROR"]

    return {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "application": "demo-api",
        "environment": "dev",
        "level": random.choice(log_level),
        "status": random.choice(statuses),
        "message": "Demo event generated by Jenkins lab",
        "response_time_ms": random.randint(20, 500),
    }


def send_events(number_of_events=10):
    with socket.create_connection(
        (LOGSTASH_HOST, LOGSTASH_PORT),
        timeout=10
    ) as sock:

        for _ in range(number_of_events):
            event = generate_event()
            message = json.dumps(event) + "\n"

            sock.sendall(message.encode("utf-8"))

            print(json.dumps(event))

            time.sleep(0.2)


if __name__ == "__main__":
    send_events()