import json
import os
import random
import socket
import time
from datetime import datetime, timezone

from kafka import KafkaProducer


LOGSTASH_HOST = "logstash"
LOGSTASH_PORT = 5000

KAFKA_HOST = "kafka"
KAFKA_PORT = 9092
KAFKA_TOPIC = "elk-jenkins-lab-logs"

BUILD_NUMBER = os.getenv("BUILD_NUMBER", "local")


def generate_event():
    statuses = ["SUCCESS", "SUCCESS", "SUCCESS", "ERROR"]
    log_level = ["INFO", "INFO", "INFO", "ERROR"]

    return {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "application": "demo-api",
        "environment": "dev",
        "build_number": BUILD_NUMBER,
        "level": random.choice(log_level),
        "status": random.choice(statuses),
        "message": "Demo event generated by Jenkins lab",
        "response_time_ms": random.randint(20, 500),
    }


def create_kafka_producer():
    return KafkaProducer(
        bootstrap_servers=f"{KAFKA_HOST}:{KAFKA_PORT}",
        value_serializer=lambda value: json.dumps(value).encode("utf-8"),
    )


def send_events(number_of_events=10):
    kafka_producer = create_kafka_producer()

    try:
        with socket.create_connection(
            (LOGSTASH_HOST, LOGSTASH_PORT),
            timeout=10
        ) as logstash_socket:

            for _ in range(number_of_events):
                event = generate_event()

                message = json.dumps(event) + "\n"

                # Send event to Logstash
                logstash_socket.sendall(message.encode("utf-8"))

                # Send event to Kafka
                kafka_producer.send(
                    KAFKA_TOPIC,
                    value=event
                )

                print(json.dumps(event))

                time.sleep(0.2)

            # Make sure all Kafka messages have been sent
            kafka_producer.flush()

    finally:
        kafka_producer.close()


if __name__ == "__main__":
    send_events()