import json
import os
import random
import time
from datetime import datetime, timezone

from kafka import KafkaProducer


KAFKA_HOST = "kafka"
KAFKA_PORT = 9092
KAFKA_TOPIC = "elk-jenkins-lab-logs"

BUILD_NUMBER = os.getenv("BUILD_NUMBER", "local")


def generate_event():
    statuses = ["SUCCESS", "SUCCESS", "SUCCESS", "ERROR"]
    log_level = ["INFO", "INFO", "INFO", "ERROR"]

    return {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "application": "demo-api",
        "environment": "dev",
        "build_number": BUILD_NUMBER,
        "level": random.choice(log_level),
        "status": random.choice(statuses),
        "message": "Demo event generated by Jenkins lab",
        "response_time_ms": random.randint(20, 500),
    }


def create_kafka_producer():
    return KafkaProducer(
        bootstrap_servers=f"{KAFKA_HOST}:{KAFKA_PORT}",
        value_serializer=lambda value: json.dumps(value).encode("utf-8"),
    )


def send_events(number_of_events=10):
    kafka_producer = create_kafka_producer()

    try:
        for _ in range(number_of_events):
            event = generate_event()

            kafka_producer.send(
                KAFKA_TOPIC,
                value=event
            )

            print(json.dumps(event))

            time.sleep(0.2)

        kafka_producer.flush()

    finally:
        kafka_producer.close()


if __name__ == "__main__":
    send_events()