input {
    tcp {
        port => 5000
        codec => json
    }
}

filter {
    mutate {
        add_field => {
            "[@metadata][index_name]" => "demo-app-elk-jenkins-%{+YYYY.MM.dd}"
        }
    }
}

output {
    stdout {
        codec => rubydebug
    }

    elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "demo-app-elk-jenkins-%{+YYYY.MM.dd}"
    }
}